### ISSUE TITLE
Download of Psalm 119 limited to 100 verses

### ISSUE THREAD

**Issue by jasonyip** [daniel-tran/meaningless#20]
Download of Psalm 119 was limited to 100 verses. Issue resolved when max_value of common.py / get_capped_integer increased from 100 to 176 in function get_capped_integer(number, min_value=1, max_value=176). Incidentally, I think get_end_of_chapter() can also be changed to return 176 since that is the maximum number of verses in any chapter of Bible i.e. Psalm 119

**Comment by jadenzaleski** [comment]
I also have this issue and @jasonyip solved it.

**Comment by daniel-tran** [comment]
This has already been addressed as part of the 1.1.0 release (see https://github.com/danieltran/meaningless/commit/78612729a535b130b9185ce8eaf23a1759710f42). Since this is the second issue that's raised this and I have a bit of time to spare, it might be worth publishing this version at some point in the near future.

**Comment by daniel-tran** [comment]
Version 1.1.0 has now been released, so this problem should be resolved now.
